export type RoadProduct = {
    slug: string;
    name: string;
    displayName: string;
    formerName?: string;
    category: string;
    eyebrow: string;
    tagline: string;
    summary: string;
    description: string;
    image: string;
    imageAlt: string;
    imageCaption: string;
    applications: string[];
    benefits: { title: string; description: string }[];
    specifications: { label: string; value: string }[];
    steps: { title: string; description: string }[];
    faqs: { question: string; answer: string }[];
    fieldNote: string;
    manufacturerPdfUrl: string;
    keywords: string[];
};

export const roadProducts: RoadProduct[] = [
    {
        slug: "dust-defeater",
        name: "Dust Defeater",
        displayName: "Fastphalt Dust Defeater",
        formerName: "Dust-X",
        category: "Dust Control",
        eyebrow: "Seal Dust",
        tagline: "Cold-pour dust control for gravel and dirt roads",
        summary: "An all-season, no-heat concentrate for controlling excessive dust on unpaved roads, farms, yards, and working surfaces.",
        description: "Dust Defeater is PCT's water-dilutable road dust treatment. It is designed for application from a water truck or distributor truck and can be diluted with up to three parts water, giving road departments and site operators a practical way to treat gravel and dirt-road dust without heated equipment.",
        image: "/images/pct/dust-defeater.webp",
        imageAlt: "Unpaved road extending through a dry rural landscape",
        imageCaption: "Unpaved-road dust-control application context.",
        applications: [
            "Gravel roads and unpaved municipal routes",
            "Dirt roads, ranch roads, and access lanes",
            "Farms and agricultural working areas",
            "Dust-prone yards and low-speed sites",
        ],
        benefits: [
            { title: "No Heat Required", description: "The manufacturer describes an all-season cold-pour formulation, eliminating heated application equipment." },
            { title: "Water Dilutable", description: "May be diluted with up to three parts water to one part product, subject to project-specific guidance." },
            { title: "Truck Applied", description: "Designed for application using a water truck or distributor truck already common to road crews." },
            { title: "OMRI Statement", description: "PCT's product sheet states that Dust Defeater carries organic certification from OMRI; confirm current certification before procurement." },
        ],
        specifications: [
            { label: "Formulation", value: "All-season cold pour" },
            { label: "Heat", value: "Not required" },
            { label: "Dilution", value: "Up to 3 parts water" },
            { label: "Equipment", value: "Water or distributor truck" },
        ],
        steps: [
            { title: "Define the treatment area", description: "Identify the gravel or dirt-road segment, traffic pattern, and dust conditions that need control." },
            { title: "Confirm the dilution", description: "Select a job-specific mix with Crownwood. PCT allows dilution with up to three parts water; Crownwood can help calculate the working strength and quantity for the road." },
            { title: "Load the application truck", description: "Prepare the selected mixture in a compatible water or distributor truck." },
            { title: "Apply and monitor", description: "Treat the road surface evenly, then monitor traffic and dust conditions to plan any maintenance application." },
        ],
        faqs: [
            { question: "Does Dust Defeater require heat?", answer: "No. PCT describes it as an all-season cold-pour formulation." },
            { question: "How is Dust Defeater applied?", answer: "The product sheet specifies a water truck or distributor truck for application." },
            { question: "How much water can be added?", answer: "PCT states that the product can be diluted with up to three parts water. Confirm the appropriate field mix for your road and traffic conditions before use." },
            { question: "Where is it intended to be used?", answer: "The manufacturer identifies gravel roads, dirt roads, and farms as primary use cases." },
        ],
        fieldNote: "Confirm coverage, application rate, curing time, package size, and maintenance interval for the specific road, traffic, and dust conditions.",
        manufacturerPdfUrl: "https://cdn.prod.website-files.com/5d1f8d8d821837c6e9a0cdb2/5d26642ab3094d81bcad1fef_ROAD%20BUILDING%20-DUSTX.pdf",
        keywords: ["Dust Defeater", "Dust-X", "gravel road dust control", "dirt road dust control", "cold pour dust control", "water truck dust control"],
    },
    {
        slug: "phpm-50",
        name: "PHPM-50",
        displayName: "PHPM-50 / FP PrimePatch",
        category: "Tack and Patch",
        eyebrow: "Tack / Prime / Patch",
        tagline: "No-heat tack membrane for pothole patching and overlays",
        summary: "PHPM-50 is a liquid-stable tack membrane for pothole patching and asphalt overlays, compatible with all patch mixes. PCT now markets it as FP PrimePatch.",
        description: "PHPM-50, now called FP PrimePatch by PCT, is a no-heat tack membrane for pothole patching and asphalt overlay work. It is formulated to seal the patch against water infiltration, remain liquid stable in application equipment, and work with all patch mixes.",
        image: "/images/pct/phpm-50.webp",
        imageAlt: "Pothole in an asphalt roadway before repair",
        imageCaption: "Pothole-repair application context for PHPM-50.",
        applications: [
            "Tack membrane for pothole repairs",
            "Asphalt overlay bonding",
            "Municipal and commercial patch programs",
            "Use with any compatible patch mix",
        ],
        benefits: [
            { title: "No Heat Required", description: "Cold-applied, all-season material that avoids heated tack equipment; protect the stored product from freezing." },
            { title: "Patch-Mix Compatible", description: "PCT specifies compatibility with all patch mixes, simplifying use across maintenance programs." },
            { title: "Liquid Stable", description: "Formulated not to gum up, become viscous, or clog application equipment." },
            { title: "Longer Patch Life", description: "PCT states that PrimePatch can increase patch life by up to five times by helping stop water infiltration." },
        ],
        specifications: [
            { label: "Known As", value: "PHPM-50" },
            { label: "PCT Name", value: "FP PrimePatch" },
            { label: "Heat", value: "Not required" },
            { label: "Certification", value: "NSF/ANSI 61 stated" },
        ],
        steps: [
            { title: "Prepare the repair", description: "Remove loose debris and prepare the pothole or overlay surface in accordance with the patch-mix and agency requirements." },
            { title: "Apply the membrane", description: "Use PrimePatch as the tack membrane. The liquid-stable formula is designed to avoid gumming or clogging equipment." },
            { title: "Place the patch mix", description: "Install the selected compatible patch mix or overlay while following its placement and compaction requirements." },
            { title: "Protect stored material", description: "No application heat is required, but PCT specifically calls for freeze protection during storage." },
        ],
        faqs: [
            { question: "Is PHPM-50 the same product as FP PrimePatch?", answer: "Yes. PHPM-50 is the familiar product name used by Crownwood customers; PCT's current product sheet markets it as FP PrimePatch." },
            { question: "Does PHPM-50 require heat?", answer: "No. PCT describes it as a no-heat, all-season material, although the stored product must be protected from freezing." },
            { question: "What patch mixes can be used?", answer: "The manufacturer states that FP PrimePatch is compatible with all patch mixes." },
            { question: "Why use a tack membrane on a patch?", answer: "PrimePatch is formulated to seal the repair from water infiltration, which PCT identifies as a cause of patch failure." },
        ],
        fieldNote: "Confirm the current storage temperature, placement procedure, traffic reopening criteria, application rate, package size, and compatibility requirements before use.",
        manufacturerPdfUrl: "https://cdn.prod.website-files.com/5d1f8d8d821837c6e9a0cdb2/5d26642380c5dd33598f480f_ROAD%20BUILDING%20-PHPM50.pdf",
        keywords: ["FP PrimePatch", "PHPM-50", "PHPM50", "cold applied tack", "pothole tack membrane", "asphalt overlay tack", "no heat tack"],
    },
    {
        slug: "banana-slide",
        name: "Banana Slide",
        displayName: "Banana Slide Asphalt Release Agent",
        category: "Equipment Release",
        eyebrow: "Release Asphalt",
        tagline: "Diesel-replacement release agent for asphalt equipment",
        summary: "A low-viscosity asphalt release treatment applied before use to truck beds, belts, hoppers, augers, tools, and other paving equipment.",
        description: "Banana Slide is PCT's environmentally friendly asphalt release solution. Applied to asphalt-handling equipment before the shift or load, it creates a release layer without using diesel and is designed for easy pump-sprayer application across the paving train.",
        image: "/images/pct/banana-slide.webp",
        imageAlt: "Paving crew working beside fresh hot-mix asphalt",
        imageCaption: "Hot-mix paving and asphalt-handling equipment.",
        applications: [
            "Dump-truck beds and material-contact surfaces",
            "Paver hoppers, augers, and conveyor belts",
            "Shovels, lutes, rakes, and hand tools",
            "Asphalt equipment prepared before material loading",
        ],
        benefits: [
            { title: "Diesel Replacement", description: "Provides an environmentally friendlier release option in place of diesel on asphalt equipment." },
            { title: "Pavement Compatible", description: "PCT states that the formula will not harm or break down the pavement." },
            { title: "High Flash Point", description: "The manufacturer highlights a high flash point as a worker-safety benefit." },
            { title: "Low Viscosity", description: "Designed for easy pump-sprayer application and longer-lasting coverage than competing release products." },
        ],
        specifications: [
            { label: "Function", value: "Asphalt release" },
            { label: "Application", value: "Pump sprayer" },
            { label: "Shelf Life", value: "8 years stated" },
            { label: "Storage", value: "No sun; protect from freezing" },
        ],
        steps: [
            { title: "Start with equipment before use", description: "Banana Slide is intended as a preventive release treatment, so apply it before asphalt contacts the equipment." },
            { title: "Cover material-contact surfaces", description: "Use a pump sprayer on truck beds, belts, hoppers, augers, and tools that will contact asphalt." },
            { title: "Reapply as operations require", description: "Inspect contact surfaces during production and ask Crownwood for a use plan based on the equipment, mix, and paving schedule." },
            { title: "Store correctly", description: "Keep the product out of direct sunlight and protect it from freezing. PCT states an eight-year shelf life." },
        ],
        faqs: [
            { question: "What equipment can Banana Slide be used on?", answer: "PCT lists tools, truck beds, belts, hoppers, and augers." },
            { question: "How is it applied?", answer: "The manufacturer calls for easy application with a pump sprayer." },
            { question: "Is Banana Slide intended to replace diesel?", answer: "Yes. PCT positions Banana Slide as an environmentally friendly diesel replacement for asphalt release." },
            { question: "How should it be stored?", answer: "Keep it out of direct sunlight and protect it from freezing. The product sheet states an eight-year shelf life." },
        ],
        fieldNote: "Confirm coverage per gallon, reapplication frequency, package sizes, surface compatibility, current SDS requirements, and the field procedure before deployment.",
        manufacturerPdfUrl: "https://cdn.prod.website-files.com/5d1f8d8d821837c6e9a0cdb2/5d266431b3094d59aaad1ff5_ROAD%20BUILDING-BANANA%20SLIDE.pdf",
        keywords: ["Banana Slide", "asphalt release agent", "diesel replacement asphalt", "truck bed release agent", "paver release agent"],
    },
    {
        slug: "fp-blacktrac",
        name: "FP Blacktrac",
        displayName: "FP Blacktrac Friction Course Sealer",
        category: "Surface Preservation",
        eyebrow: "Sealer Blacktrac",
        tagline: "Sprayable membrane sealer for low-volume hot-mix roads",
        summary: "A fast-drying, no-heat friction-course sealer that maintains the appearance of low-volume asphalt roads.",
        description: "FP Blacktrac is PCT's sprayable, environmentally conscious membrane sealer for low-volume hot-mix asphalt roads. The liquid-stable formula is designed for straightforward spraying, fast dry times, and equipment reliability without heating.",
        image: "/images/pct/fp-blacktrac.webp",
        imageAlt: "Dark asphalt roadway with a yellow centerline",
        imageCaption: "Low-volume asphalt preservation context.",
        applications: [
            "Low-volume asphalt road preservation",
            "Hot-mix asphalt surface treatment",
            "Appearance renewal on aging pavement",
            "Planned preventive-maintenance programs",
        ],
        benefits: [
            { title: "Easy to Spray", description: "Developed as a spray-applied friction-course sealer for efficient road treatment." },
            { title: "No Heat Required", description: "All-season material with fast dry times and no heating requirement." },
            { title: "Liquid Stable", description: "Formulated not to gum, thicken, or clog application equipment." },
            { title: "Service-Life Extension", description: "PCT states that Blacktrac can increase road life by up to five years, with a treatment life of two to three years." },
        ],
        specifications: [
            { label: "Surface", value: "Hot-mix asphalt" },
            { label: "Road Type", value: "Low volume" },
            { label: "Treatment Life", value: "2-3 years stated" },
            { label: "Road-Life Gain", value: "Up to 5 years stated" },
        ],
        steps: [
            { title: "Evaluate the pavement", description: "Confirm that the project is a low-volume hot-mix surface suited to preventive membrane treatment rather than structural rehabilitation." },
            { title: "Set the application plan", description: "Establish surface preparation, coverage, traffic control, and spray-equipment settings with Crownwood for the specific pavement and operating conditions." },
            { title: "Spray the treatment", description: "Apply with compatible spray equipment. The material is designed to remain liquid stable and avoid clogging." },
            { title: "Allow the surface to dry", description: "PCT identifies fast dry times, but no fixed reopening time is published; use the current technical guidance and site conditions." },
        ],
        faqs: [
            { question: "What surfaces are compatible with FP Blacktrac?", answer: "PCT specifies compatibility over all hot-mix surfaces and positions the product for low-volume asphalt roads." },
            { question: "Does it require heating?", answer: "No. The manufacturer describes FP Blacktrac as an all-season, no-heat material." },
            { question: "How long does a treatment last?", answer: "PCT states a two-to-three-year treatment life and says the product can increase road life by up to five years. Actual performance depends on pavement condition, preparation, traffic, climate, and application." },
            { question: "Will it clog spray equipment?", answer: "The product sheet describes the formula as liquid stable and says it will not gum, become viscous, or clog equipment." },
        ],
        fieldNote: "Confirm application rate, dry-time range, dilution, surface preparation, spray equipment, and traffic reopening requirements for each project.",
        manufacturerPdfUrl: "https://cdn.prod.website-files.com/5d1f8d8d821837c6e9a0cdb2/5d26642e8836af1328eb6bc2_ROAD%20BUILDING-BLACKTRAC.pdf",
        keywords: ["FP Blacktrac", "friction course sealer", "low volume road sealer", "hot mix surface sealer", "sprayable asphalt sealer"],
    },
    {
        slug: "rumbleguard",
        name: "Rumbleguard",
        displayName: "Rumbleguard Pavement Preservative",
        category: "Safety Preservation",
        eyebrow: "Preserve Rumble Strips",
        tagline: "Preventive treatment for milled rumble strips and surrounding pavement",
        summary: "A pavement-preservation treatment designed to slow wear, UV deterioration, cracking, and water infiltration around rumble strips.",
        description: "Rumbleguard is PCT's targeted preservation product for rumble strips. It is formulated to revitalize pavement properties lost through wear and UV exposure, helping keep milled strips intact and functional while delaying larger rehabilitation work.",
        image: "/images/pct/rumbleguard.webp",
        imageAlt: "Highway markings and rumble-strip corridor",
        imageCaption: "Rumble-strip preservation and roadway-safety context.",
        applications: [
            "Centerline and shoulder rumble strips",
            "Milled rumble-strip preservation",
            "Preventive maintenance before chipping or flattening",
            "Water-infiltration control around safety features",
        ],
        benefits: [
            { title: "Protects the Safety Feature", description: "Helps keep rumble strips intact so they continue alerting drivers who drift from the travel lane." },
            { title: "Slows Deterioration", description: "Designed to revitalize pavement affected by wear and UV exposure and to seal small cracks against water." },
            { title: "Delays Major Work", description: "Preventive treatment can postpone full-depth repair, overlays, and reconstruction around the milled strip." },
            { title: "Preserves Prior Investment", description: "Targets the pavement and rumble-strip asset already in place rather than waiting for functional failure." },
        ],
        specifications: [
            { label: "Asset", value: "Milled rumble strips" },
            { label: "Strategy", value: "Preventive preservation" },
            { label: "Primary Threats", value: "Wear, UV, water" },
            { label: "Goal", value: "Delay rehabilitation" },
        ],
        steps: [
            { title: "Inspect the rumble strip", description: "Document chipping, flattening, cracking, wear, and water-entry points before selecting a preservation treatment." },
            { title: "Confirm preservation fit", description: "Separate candidates for preventive treatment from sections that already require structural repair or rehabilitation." },
            { title: "Build the treatment plan", description: "Ask Crownwood to confirm preparation, application method, coverage, and reopening requirements for the roadway and traffic plan." },
            { title: "Track condition over time", description: "Monitor the treated safety feature so future maintenance is scheduled before the strip loses function." },
        ],
        faqs: [
            { question: "What does Rumbleguard protect?", answer: "It is intended for rumble strips and the pavement immediately around milled rumble strips, which PCT notes can be more prone to wear." },
            { question: "How can it support roadway safety?", answer: "By helping preserve the shape and condition of the strip, the treatment supports the audible and tactile warning that alerts drifting drivers." },
            { question: "Is this a structural repair product?", answer: "The product sheet presents Rumbleguard as preventive preservation. Severely failed pavement may still require repair, overlay, or reconstruction." },
            { question: "How is the application rate determined?", answer: "Coverage, preparation, application method, and reopening time should be confirmed for the pavement condition, rumble-strip geometry, and traffic plan." },
        ],
        fieldNote: "Confirm composition, compatible application equipment, coverage, curing time, package size, certification, and traffic reopening requirements for the roadway.",
        manufacturerPdfUrl: "https://cdn.prod.website-files.com/5d1f8d8d821837c6e9a0cdb2/67fe85b47e3ff212cbb7c273_RUMBLE%20STRIP%20.pdf",
        keywords: ["Rumbleguard", "rumble strip preservation", "milled rumble strip sealer", "road safety preservation", "rumble strip maintenance"],
    },
    {
        slug: "eco-black",
        name: "Eco Black",
        displayName: "Fastphalt Eco Black (COS-50)",
        formerName: "COS-50",
        category: "Surface Renewal",
        eyebrow: "Seal Surface",
        tagline: "No-heat sealer for low-speed asphalt and chip-seal surfaces",
        summary: "A surface-sealing treatment for renewing appearance and limiting water entry on residential streets, parking lots, and other low-speed roads.",
        description: "Eco Black is PCT's no-heat treatment for sealing and renewing asphalt and chip-seal surfaces. It is aimed at low-speed pavement where appearance and protection against water reaching the base are central maintenance goals.",
        image: "/images/pct/eco-black.webp",
        imageAlt: "Finished black asphalt highway crossing an open landscape",
        imageCaption: "Finished low-speed asphalt surface.",
        applications: [
            "Residential asphalt streets",
            "Parking lots and low-speed paved areas",
            "Chip-seal surface renewal",
            "Water-sealing preventive maintenance",
        ],
        benefits: [
            { title: "No Heat Required", description: "Cold-applied surface treatment without heated material or kettles." },
            { title: "Two Surface Types", description: "PCT specifies compatibility with both asphalt and chip-seal surfaces." },
            { title: "Water Sealing", description: "Designed to help prevent water from reaching the pavement base and contributing to deterioration." },
            { title: "NSF/ANSI 61 Statement", description: "The product sheet states that Eco Black is NSF/ANSI 61 certified for drinking-water-contact materials; confirm current certification." },
        ],
        specifications: [
            { label: "Surface", value: "Asphalt / chip seal" },
            { label: "Traffic", value: "Low-speed roads" },
            { label: "Heat", value: "Not required" },
            { label: "Certification", value: "NSF/ANSI 61 stated" },
        ],
        steps: [
            { title: "Confirm the pavement use", description: "Use on asphalt or chip seal serving a residential street, parking lot, or other low-speed road." },
            { title: "Assess repair needs", description: "Address structural failures separately; Eco Black is presented as a sealing and appearance-renewal treatment." },
            { title: "Set the field specification", description: "Confirm cleaning, application equipment, coverage, drying, and traffic-control requirements with Crownwood before work begins." },
            { title: "Apply without heat", description: "Install the no-heat treatment under the current technical guidance and reopen only after the specified condition is reached." },
        ],
        faqs: [
            { question: "Can Eco Black be used on chip seal?", answer: "Yes. PCT lists both asphalt and chip-seal surfaces as compatible." },
            { question: "What kind of roads is it intended for?", answer: "The manufacturer identifies residential streets, parking lots, and other low-speed roads." },
            { question: "What does the treatment do?", answer: "Eco Black renews the appearance of the pavement and seals against water entering the base, which PCT says can help increase pavement life." },
            { question: "Does it need to be heated?", answer: "No. The product sheet explicitly states that no heat is required." },
        ],
        fieldNote: "Confirm coverage, dilution, dry time, preparation, skid data, package sizes, and current NSF/ANSI 61 documentation during procurement.",
        manufacturerPdfUrl: "https://cdn.prod.website-files.com/5d1f8d8d821837c6e9a0cdb2/5d26642fc7f84cb1ceee40c3_ROAD%20BUILDING-COS50%20%281%29.pdf",
        keywords: ["Fastphalt Eco Black", "COS-50", "asphalt surface renewal", "chip seal sealer", "low speed road sealer", "parking lot sealer"],
    },
    {
        slug: "bam",
        name: "BAM",
        displayName: "BAM Bonding Adhesive Material",
        category: "Pothole and Shoulder Repair",
        eyebrow: "Bonding Adhesive Material",
        tagline: "Ready-to-use binder for spray-injection and stockpile patching",
        summary: "A no-heat liquid bonding agent for spray-injection pothole patchers, rural shoulders, stockpile mixes, and throw-and-roll repairs.",
        description: "BAM - Bonding Adhesive Material - is PCT's ready-to-use liquid binder for spray-injection pothole and shoulder repair. It can also be mixed with rock to create a stockpile patch mix for lower-cost pothole work and throw-and-roll placement.",
        image: "/images/pct/bam.webp",
        imageAlt: "Road crew applying a dark repair treatment along a pavement edge",
        imageCaption: "Road-repair application context for BAM.",
        applications: [
            "Spray-injection pothole patchers",
            "Rural road shoulder repair",
            "Stockpile patch mix made with rock",
            "Throw-and-roll pothole applications",
        ],
        benefits: [
            { title: "Ready to Use", description: "Supplied as a no-heat liquid bonding agent for road-maintenance operations." },
            { title: "Two Patch Workflows", description: "Use with spray-injection patchers or mix with rock for stockpile and throw-and-roll repairs." },
            { title: "Non-Clogging / Non-Settling", description: "PCT describes BAM as non-clogging and non-settling for easier field application." },
            { title: "Immediate Traffic", description: "The manufacturer states that BAM repairs can accept immediate traffic, minimizing disruption." },
        ],
        specifications: [
            { label: "Type", value: "Liquid bonding agent" },
            { label: "Heat", value: "Not required" },
            { label: "Application", value: "Injection / stockpile" },
            { label: "Traffic", value: "Immediate, per PCT" },
        ],
        steps: [
            { title: "Choose the repair method", description: "Use BAM through a compatible spray-injection pothole patcher or build a stockpile mix with suitable rock." },
            { title: "Set the mix and equipment", description: "Confirm aggregate, binder amount, equipment settings, and job procedure with Crownwood for the selected repair method." },
            { title: "Place the repair", description: "Install the spray-injection, shoulder, stockpile, or throw-and-roll repair using the selected field method." },
            { title: "Return to service", description: "PCT states that BAM allows immediate traffic, subject to the completed repair meeting project and agency requirements." },
        ],
        faqs: [
            { question: "What does BAM stand for?", answer: "BAM stands for Bonding Adhesive Material." },
            { question: "Is BAM only for spray-injection patchers?", answer: "No. PCT also says BAM can be mixed with rock to create a stockpile patch mix for throw-and-roll use and identifies rural shoulder repair as an application." },
            { question: "Does BAM require heating?", answer: "No. The manufacturer describes it as ready to use with no heating required." },
            { question: "What durability does PCT claim?", answer: "PCT states that applications with BAM last up to ten times longer than conventional pothole repairs. Actual results depend on materials, preparation, placement, traffic, and site conditions." },
        ],
        fieldNote: "Confirm current certification, SDS requirements, aggregate selection, binder rate, packaging, equipment compatibility, and agency acceptance before purchasing.",
        manufacturerPdfUrl: "https://cdn.prod.website-files.com/5d1f8d8d821837c6e9a0cdb2/67fe82fce2aa71c54f01c5a5_BAM%20%281%29.pdf",
        keywords: ["BAM bonding adhesive material", "spray injection pothole patch", "stockpile patch binder", "shoulder repair binder", "throw and roll patch"],
    },
    {
        slug: "monkey-business",
        name: "Monkey Business",
        displayName: "Monkey Business Asphalt Cleaner",
        category: "Equipment Cleaning",
        eyebrow: "Clean Asphalt",
        tagline: "D-limonene cleaner for grease, tar, and asphalt buildup",
        summary: "An all-natural, water-dilutable D-limonene cleaner for removing asphalt, tar, and grease from road-building equipment.",
        description: "Monkey Business is PCT's D-limonene-based cleaner for asphalt buildup. The no-solvent-formulation cleaner targets grease, tar, and asphalt and may be diluted with up to five parts water for equipment and tool cleanup.",
        image: "/images/pct/monkey-business.webp",
        imageAlt: "Road roller used during asphalt paving operations",
        imageCaption: "Asphalt-equipment cleaning and maintenance context.",
        applications: [
            "Asphalt buildup on paving equipment",
            "Tar and grease removal",
            "Road-building tools and material-contact surfaces",
            "Routine paving-fleet cleanup",
        ],
        benefits: [
            { title: "D-Limonene Based", description: "Uses a citrus-derived cleaning ingredient identified by PCT as an all-natural solution." },
            { title: "Broad Asphalt Cleanup", description: "PCT states that the cleaner removes greases, tars, and asphalts." },
            { title: "Water Dilutable", description: "May be diluted with up to five parts water to match the cleaning task." },
            { title: "Environmentally Friendly", description: "Positioned by PCT as an environmentally friendly alternative for asphalt-equipment cleaning." },
        ],
        specifications: [
            { label: "Base", value: "D-limonene" },
            { label: "Targets", value: "Grease / tar / asphalt" },
            { label: "Dilution", value: "Up to 5 parts water" },
            { label: "Use", value: "Equipment cleaning" },
        ],
        steps: [
            { title: "Identify the buildup", description: "Determine whether the surface needs removal of grease, tar, asphalt, or a combination of deposits." },
            { title: "Choose the dilution", description: "Match the working strength to the cleaning task. PCT permits dilution with up to five parts water; Crownwood can help choose the starting mix for the equipment and buildup." },
            { title: "Confirm surface compatibility", description: "Review the current SDS and test an inconspicuous area before broad use, especially on coatings, plastics, seals, or sensitive finishes." },
            { title: "Clean and manage residue", description: "Use the confirmed field procedure and collect or manage loosened asphalt residue in accordance with site requirements." },
        ],
        faqs: [
            { question: "What does Monkey Business remove?", answer: "PCT lists greases, tars, and asphalts." },
            { question: "What is the active cleaning base?", answer: "The product sheet identifies Monkey Business as a D-limonene solution." },
            { question: "Can it be diluted?", answer: "Yes. PCT says it may be diluted with up to five parts water." },
            { question: "Is it the same as an asphalt release agent?", answer: "The product sheet positions Monkey Business as a cleaner and remover. For preventive asphalt release before equipment use, PCT lists Banana Slide as a separate product." },
        ],
        fieldNote: "Confirm dwell time, package size, substrate compatibility, rinsing procedure, PPE, residue handling, and current SDS instructions before use.",
        manufacturerPdfUrl: "https://cdn.prod.website-files.com/5d1f8d8d821837c6e9a0cdb2/5d266430c7f84c1ee2ee40c4_ROAD%20BUILDING.pdf",
        keywords: ["Monkey Business asphalt cleaner", "D-limonene asphalt cleaner", "tar remover", "paving equipment cleaner", "asphalt buildup remover"],
    },
];

export function getRoadProduct(slug: string) {
    return roadProducts.find((product) => product.slug === slug);
}
